name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Snyk Test
    environment: snyk-npm
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # or node_modules, depending on where npm install puts dependencies
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
          
      # Install Snyk, auth snyk and Snyk to HTML
      - name: Setup Snyk + snyk-to-html
        run: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth ${{secrets.SNYK_AUTH}}
          # Create a directory to hold the reports
          mkdir -p snyk-reports 

# --- Snyk Open Source (SCA) ---

      - name: Snyk Open Source Test and HTML Report
        run: |
          snyk test --json > snyk-reports/oss-results.json || true
          snyk-to-html -i snyk-reports/oss-results.json -o snyk-reports/results-opensource.html
        continue-on-error: false
        
      - name: Snyk Open Source Monitor (Send results to Snyk Platform)
        run: |
          snyk monitor 
        continue-on-error: true

# --- Snyk Code (SAST) ---

      - name: Snyk Code Test, Report (Send results to Snyk Platform) 
        run: |
          # Extract just the repository name from the owner/repo-name format
          REPO_NAME=$(basename ${{ github.repository }})
          PROJECT_NAME="$REPO_NAME-code"
      
          snyk code test --report --project-name="$PROJECT_NAME" 
        
        continue-on-error: true
        
      - name: Snyk Code Test and HTML report
        run: |
          snyk code test --json | tee snyk-reports/code-results-raw.json || true
          snyk-to-html -i snyk-reports/code-results-raw.json -o snyk-reports/results-code.html
        continue-on-error: false
        
# --- Artifact Upload (Combined) ---
      
      - name: Upload Snyk Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snyk-Security-Reports
          # Upload the entire folder containing all reports
          path: snyk-reports/
